version: 2
python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
sphinx:
  builder: dirhtml
  fail_on_warning: true
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
